;;===============================
;;Name: Yunpeng Fan
;;===============================

.orig x3000

; CODE GOES HERE :D

	AND R1,R1,0;	CLEAR R1
	LD R1,LENGTH;	STORE LENGTH OF ARRAY  
	AND R2,R2,0;	CLEAR R2
	LD R2,ARRAY;	STORE ADDRESS OF ARRAY
	AND R3,R3,0;	CLEAR R3
	AND R4,R4,0; 	CLEAR R4
	AND R5,R5,0; 	CLEAR R5
	AND R6,R6,0;	CLEAR R6
	AND R7,R7,0;	CLEAR R7
		
KFORLP	AND R0,R0,0;	CLEAR R0 TO STORE VALUE OF ISSORTED
	ADD R0,R0,1;	SET ISSORTED = 1
	LD R2,ARRAY;	STORE ADDRESS OF ARRAY
	ADD R1,R1,-1;	FUNCTION AS K++
	BRn STOP;	JUMP TO STOP IF KFORLP IS DONE	
	ADD R6,R1,0;	STORE CURRENT VALUE OF K INTO R6
	BR IFORLP;	STRAT IFORLP

IFORLP	ADD R6,R6,-1;	FUNCTION AS I++
	BRn KFORLP;	IF NO MORE ELEMENT JUMP BACK TO KFORLP
	LDR R3,R2,0;	STORE VALUE OF ARRAY[I-1]
	ADD R2,R2,1;	ADDRESS++ TO GET NEXT ELEMENT
	LDR R4,R2,0;	STORE VALUE OF ARRAY[I]
	NOT R4,R4;	1ST STEP TO GET -R4
	ADD R4,R4,1;	2ND STEP TO GET -R4
	ADD R7,R3,R4;	SEE IF ARRAY[I] < ARRAY[I-1]
	BRp SWITCH;	IF YES JUMP TO SWITCH TO SWITCH POSITION IN ARRAY
	BRnz IFORLP;	IF NO JUMP BACK TO IFORLP
		
SWITCH	NOT R4,R4;	1ST STEP TO GET -R4
	ADD R4,R4,1;	2ND STEP TO GET -R4
	ADD R5,R4,0;	STORE ARRAY[I] AS TEMP
	ADD R4,R3,0;	TRANFER ARRAY[I-1] TO ARRAY[I]
	STR R4,R2,0;	STORE VALUE OF ARRAY[I] IN TO ADDRESS OF ARRAY[I]
	ADD R3,R5,0;	TRANSFER ARRAY[I] TO ARRAY[I-1]
	STR R3,R2,-1;	STORE VALUE OF ARRAY[I] IN TO ADDRESS OF ARRAY[I]
	AND R0,R0,0;	SET ISSORTED = 0
	BR IFORLP;

STOP	OUT;		RETURN IF ARRAY ISSORTED
	HALT;		STOP

ARRAY   .fill x6000
LENGTH  .fill 12
.end

.orig x6000
.fill 28
.fill -50
.fill 7
.fill 0
.fill 216
.fill 4
.fill 15
.fill -82
.fill 34
.fill 101
.fill -5
.fill 61
.end

