;;===============================
;;Name: Yunpeng Fan
;;===============================

.orig x3000

; CODE GOES HERE! :D
	
	AND R0,R0,0;	CLEAR R0
	AND R1,R1,0;	CLEAR R1	
	AND R2,R2,0;	CLEAR R2		
	AND R3,R3,0;	CLEAR R3	
	AND R4,R4,0;	CLEAR R4	

	LD R1,NUMBER;	STORE 9 INTO R1				
	NOT R1,R1;	1ST STEP TO GET 2'S COMPLEMENT OF R1	
	ADD R1,R1,1;	2ND STEP. R1:-9			
	LD R2,LENGTH;	STORE LENGTH ARRAY TO R2	
	LD R3,ARRAY;	STORE ADDRESS OF ARRAY INTO R3	

WHILE 	LDR R4,R3,0;	STORE ADDRESS OF CURRENT ELEMENT IN ARRAY		
	ADD R4,R1,R4;	R4 = R4 - 9					
	BRz COUNT;	JUMP TO COUNT IF R4 - 9 = 0		
	ADD R3,R3,1;	INCREMENT ADDRESS TO GET NEXT ELEMENT		
	ADD R2,R2,-1;	COUNT HOW MANY ELEMENTS ARE LEFT		
	BRz STOP;	JUMP TO STOP IF NO MORE ELEMENTS LEFT		
	BR WHILE;	COUNT AGAIN FROM NEXT ELEMENT IF THERE ARE MORE ELEMENTS		

COUNT 	ADD R0,R0,1;	IF AN ELEMENT IS MULTIBLE OF 9, COUNT+1
	ADD R3,R3,1;	INCREMENT ADDRESS TO GET NEXT ELEMENT		
	ADD R2,R2,-1;	COUNT HOW MANY ELEMENTS ARE LEFT	
	BRz STOP;	JUMP TO STOP IF NO MORE ELEMENTS LEFT
	BR WHILE;	JUMP BACK TO WHILE TO STRAT WITH A NEW ELEMENT		

STOP 	OUT;		RETURN COUNT		
	HALT;		STOP			

NUMBER  .fill 9;		
ARRAY   .fill x6000;		
LENGTH  .fill 10;		
ANSWER	.fill 0;	
.end;			

.orig x6000
.fill 8
.fill 9
.fill 7
.fill 0
.fill -3
.fill 11
.fill 9
.fill -9
.fill 2
.fill 9
.end
